alertmanager:
  persistentVolume:
    enabled: true
    storageClass: ibmc-file-bronze
    accessModes:
    - ReadWriteOnce
  service:
    type: NodePort
    nodePort: 31010

alertmanagerFiles:
  alertmanager.yml:
    global:
      slack_api_url: 'https://hooks.slack.com/services/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'

    route:
      receiver: 'slack-notifications'
      group_wait: 10s
      group_interval: 5m
      repeat_interval: 3h
      routes:
      - receiver: 'slack-notifications'
        group_wait: 10s

    receivers:
      - name: 'slack-notifications'
        slack_configs:
        - channel: '#alert-manager-sec'
          send_resolved: true

server:
  name: prometheus
  persistentVolume: 
    enabled: true
    storageClass: ibmc-file-bronze
    accessModes:
    - ReadWriteOnce
  service:
    type: NodePort
    nodePort: 31012

serverFiles:
  prometheus.yml:
    scrape_configs:
    - job_name: prometheus
      static_configs:
        - targets:
          - localhost:9090
    - job_name: mysql_exporter1
      scrape_interval: 1m
      metrics_path: /metrics
      static_configs:
        - targets: ['prometheus1.seoul01.jp-tok.containers.mybluemix.net:32206']
    - job_name: dy_exporter
      scrape_interval: 1m
      metrics_path: /metrics
      static_configs:
        - targets: ['169.56.109.198:9100']
    - job_name: 'federate'
      scrape_interval: 1m
      honor_labels: true
      metrics_path: '/federate'
      params:
        'match[]':
          - '{job="prometheus"}'
          - '{__name__=~"job:.*"}'
      static_configs:
        - targets:
          - '169.56.109.201:9090' 
          - '198.11.193.253:9090'
