alertmanager:
  persistentVolume:
    enabled: true
    storageClass: ibmc-file-bronze
    accessModes:
    - ReadWriteOnce
  service:
    type: NodePort
    nodePort: 31010

alertmanagerFiles:
  alertmanager.yml:
    global:
      slack_api_url: 'https://hooks.slack.com/services/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'

    route:
      receiver: 'slack-notifications'
      group_wait: 10s
      group_interval: 5m
      repeat_interval: 3h
      routes:
      - receiver: 'slack-notifications'
        group_wait: 10s

    receivers:
      - name: 'slack-notifications'
        slack_configs:
        - channel: '#alert-manager-sec'
          send_resolved: true

server:
  name: prometheus
  persistentVolume: 
    enabled: true
    storageClass: ibmc-file-bronze
    accessModes:
    - ReadWriteOnce
  service:
    type: NodePort
    nodePort: 31011

serverFiles:
  prometheus.yml:
    scrape_configs:
    - job_name: prometheus
      static_configs:
        - targets:
          - localhost:9090

